### ISSUE TITLE
Configure host and concurrent connections

### ISSUE THREAD

**Issue by d3cline** [saltcorn/saltcorn#1024]
I want to run saltcorn within a user environment where I do not have root. This should be possible as the host provides Postgres and other options which are on API endpoints. When trying to deploy I ran into some issues. 

```
$ ./node_modules/.bin/saltcorn serve -p 43668
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:43668
    at listenOnMasterHandle (net.js:1385:18)
    at rr (internal/cluster/child.js:138:12)
    at Worker.<anonymous> (internal/cluster/child.js:105:7)
    at process.onInternalMessage (internal/cluster/utils.js:48:5)
    at process.emit (events.js:388:22)
    at process.emit (domain.js:470:12)
    at processEmit [as emit] (/home/aesop/apps/saltcorn/node_modules/@saltcorn/cli/node_modules/signal-exit/index.js:161:32)
    at emit (internal/child_process.js:910:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
Emitted 'error' event on Server instance at:
    at listenOnMasterHandle (net.js:1386:21)
    at rr (internal/cluster/child.js:138:12)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 43668
}
```

If I do not specify port I get a different error, 

```
error: too many connections for role "saltcorn"
    Code: 53300
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:839:20)
    at process.target.send (internal/child_process.js:710:19)
    at sendHelper (internal/cluster/utils.js:27:15)
    at send (internal/cluster/child.js:199:10)
    at EventEmitter.cluster._setupWorker (internal/cluster/child.js:49:3)
    at initializeClusterIPC (internal/bootstrap/pre_execution.js:363:13)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:60:3)
    at internal/main/run_main_module.js:7:1
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:30:12)
    at process.emit (events.js:376:20)
    at internal/child_process.js:843:39
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

How can I run in serve mode within these limits?

**Comment by glutamate** [comment]
@d3cline there should be no problem running Saltcorn as non-root, indeed this is strongly recommended and on the digital ocean images Saltcorn runs as a standard user.

If you want to access port 80 as non-root you have to configure your OS to allow this, [ here ](https://github.com/saltcorn/saltcorn/blob/master/deploy/digitalocean-marketplace/scripts/10-install-node#L3) is how it is done on the digital ocean images - but I don't think that is your problem here.

First make sure that there are no orphaned saltcorn processes running in the background with `ps aux | grep saltcorn` (psql idle connections are okay, that doesn't matter). If there are any node processes says running, killed them manually or with `killall node` - or restart your OS

Then try launching saltcorn with a more standard port number, e.g. 3001 `saltcorn serve -p 3001`. If this works, there might be some limits on the higher part numbers that you can access.

If they're still doesn't work, I'm not quite sure what to do. Try running the very simple [node HTTP server](https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTP-server/).

**Comment by d3cline** [comment]
Thanks. I tried the `-p` flag but ran into the pasted errors. I am using Opalstack which is a managed host which provides api endpoints to create the shell user and the database. I want to write an automated install script for the platform, and have ran into the issues pasted. But the alternative deployment might work. Have you or anyone else who might read this deployed using a different method/server then the one documented?
