### ISSUE TITLE
Searchbar bugged in 0.8.1-beta.3

### ISSUE THREAD

**Issue by Txikivasco** [saltcorn/saltcorn#1535]
description of the bug:

after updating to 0.8.1-beta.3 I get this error when using the searchbar:

"An error occurred
Cannot read properties of undefined (reading 'runMany')
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation."

It worked fine in the previous version, showing a "show" view for every row containing the string entered in the search field

**Comment by Txikivasco** [comment]
id | 104
-- | --
stack | TypeError: Cannot read properties of undefined (reading 'runMany')     at runSearch (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/search.js:180:31)     at /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/search.js:257:7
message | Cannot read properties of undefined (reading 'runMany')
occur_at | Thu Dec 22 2022 11:17:03 GMT+0100 (hora estándar de Europa central)
tenant | public
user_id | 1
body | {   "body": {} }
url | /search?q=ur
headers | {   "host": "kisib.arkeoworks.eus",   "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",   "cookie": "connect.sid=s%3ApQ1MyxyoohOEQ3gi88rTJmgzlnoeKKBv.e9ZVVtI2zmuno6lvoGovs3lNUwT%2F2gRIelCsAhaNJVI",   "referer": "http://kisib.arkeoworks.eus/page/B%C3%BAsqueda",   "x-real-ip": "185.193.9.137",   "connection": "close",   "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",   "accept-encoding": "gzip, deflate",   "accept-language": "es-ES,es;q=0.9",   "x-forwarded-for": "185.193.9.137",   "x-forwarded-proto": "http",   "x-forwarded-scheme": "http",   "upgrade-insecure-requests": "1" }

**Comment by Txikivasco** [comment]
You're right, the view was missing in the search configuration.
