### ISSUE TITLE
Building mobile apps fails

### ISSUE THREAD

**Issue by mariusst** [saltcorn/saltcorn#1553]
Hi there,

I have latest saltcorn installed on debian 11. When I try to build android or ios package I receive this error

> spawn saltcorn ENOENT
Error: spawn saltcorn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

What do I need to build mobile packages

**Comment by AleksandrSokolov** [comment]
Please see https://github.com/saltcorn/saltcorn/issues/1343

**Comment by mariusst** [comment]
> Please see #1343

Thank you. I will try it.

**Comment by christianhugoch** [comment]
Hi, can you run a "saltcorn info" and send me the "cliPath" output?

And if it is a systemctl service the output from

sudo systemctl cat  saltcorn.service

**Comment by mariusst** [comment]
> Hi, can you run a "saltcorn info" and send me the "cliPath" output?
> 
> And if it is a systemctl service the output from
> 
> sudo systemctl cat saltcorn.service

Hi Christian,

Here it is:

`cliPath: /home/marius/.local/lib/node_modules/@saltcorn/cli/src/commands`

and 

```
# /lib/systemd/system/saltcorn.service
[Unit]
Description=saltcorn
Documentation=https://saltcorn.com
After=network.target

[Service]
Type=notify
WatchdogSec=5
User=marius
WorkingDirectory=/home/marius
ExecStart=/home/marius/.local/bin/saltcorn serve -p 8080
Restart=always
Environment="NODE_ENV=production"

[Install]
WantedBy=multi-user.target
```

I will also like to mention that I tried to build the docker image on my own following the instructions from #1343 but it didn't work, although it seems that the image was build successfully. This is the error I got when trying to build android app from the backend:

```
spawn saltcorn ENOENT
Error: spawn saltcorn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
