### ISSUE TITLE
0.8.1rc2 diagram: TypeError: trigger.getTags is not a function

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1577]
**Describe the bug**
Was just checking the diagram after restoring backup. Not even sure it's related since tags are new stuff right?
```
TypeError: trigger.getTags is not a function
    at ExtractHelper.handleTableTrigger (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/diagram/node_extract_utils.ts:310:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExtractHelper.addTableNode (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/diagram/node_extract_utils.ts:281:32)
    at ExtractHelper.handleNodeConnections (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/diagram/node_extract_utils.ts:234:11)
    at ExtractHelper.addEmbeddedView (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/diagram/node_extract_utils.ts:259:7)
    at ExtractHelper.handleNodeConnections (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/diagram/node_extract_utils.ts:219:11)
    at buildTree (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/diagram/node_extract_utils.ts:100:7)
    at buildObjectTrees (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/diagram/node_extract_utils.ts:78:23)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/diagram.js:90:42
```

**To Reproduce**
1. Tenant
2. Restore
3. Go to diagram

**Expected behavior**
show the nice diagram (that should keep the zoom and be movable, that's my embeded FR)

**Comment by christianhugoch** [comment]
I believe this happened because of a virtual trigger. For example, The 'room' view template has a virtual trigger that fires when you insert something into the messages table. Those trigger don't have all properties like a trigger from the db.
The fix is already merged.
https://github.com/saltcorn/saltcorn/pull/1604

**Comment by j2l** [comment]
Thank you @christianhugoch and @glutamate !
Closing in advance
