### ISSUE TITLE
internet access via a proxy server

### ISSUE THREAD

**Issue by RogueSnipa** [saltcorn/saltcorn#1587]
My saltcorn docker container has working internet access via a proxy server. 
```
root@0b289d83a6e7:/# curl https://store.saltcorn.com/api/extensions | grep -io \"id\": | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11714  100 11714    0     0  29066      0 --:--:-- --:--:-- --:--:-- 29066
     53      53     318
```
But in the app I can't access the ModuleStore endpoint (http://ServerIp:3000/plugins ).
How can saltcorn use an internet connection via a proxy server?

**Comment by Tacioandrade** [comment]
Hello, my friend! In cases like this, it is not saltcorn that has to be configured to use the proxy but your Linux server. In general, the simplest option is to release the IP of your server where the container is installed to pass outside the proxy, if this is not possible, then you will have to configure the proxy directly in Linux.

In case your proxy is unauthenticated, you can add this environment variable in /etc/bash.bashrc or elsewhere:
export http_proxy=http://proxy-id:port

Now if the proxy is authenticated, I don't know how it should be done, because I never needed to do it.

I recommend passing this export there also to your container, either directly through docker-compose or through docker run.

**Comment by RogueSnipa** [comment]
I believe that I have internet access inside the container.
```
root@b6e440b0ffb6:/# export
declare -x HOME="/root"
declare -x HOSTNAME="b6e440b0ffb6"
declare -x HTTPS_PROXY="http://▒▒▒▒▒▒▒▒▒▒▒▒▒▒:3128"
declare -x HTTP_PROXY="http://▒▒▒▒▒▒▒▒▒▒▒▒▒▒:3128"
declare -x NODE_ENV="production"
declare -x NODE_VERSION="16.13.2"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PGDATABASE="▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
declare -x PGHOST="▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
declare -x PGPASSWORD="▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
declare -x PGUSER="▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
declare -x PWD="/"
declare -x SALTCORN_DISABLE_UPGRADE="true"
declare -x SALTCORN_SESSION_SECRET="▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
declare -x SHLVL="1"
declare -x TERM="xterm"
declare -x YARN_VERSION="1.22.15"

root@b6e440b0ffb6:/# curl https://store.saltcorn.com/api/packs?fields=name,description
{"success":[{"name":"Todo list","description":"Simple todo list"},{"name":"Issue  tracker","description":"Track bugs or feedback"},{"name":"Project management","description":"Assignable tasks, projects, kanban board"},{"name":"Address book","description":"Contact list with meeting notes"},{"name":"Blog","description":"Blog with rich-text post and comments"},{"name":"Project-employee assignment","description":"Example of building interfaces based on many to many relationships"},{"name":"Saltcorn store","description":"The plugin and pack store running on store.saltcorn.com"},{"name":"Software directory","description":"Open-Source No-Code Directory"},{"name":"Location display and search","description":"Location-based search with map display"},{"name":"Link sharing","description":"Hacker news clone:  link sharing and discussion"},{"name":"File transfer service","description":"Allow anonymous users to upload files"},{"name":"French Vocabulary","description":"Flash cards with French-English dictionary"},{"name":"Roadmap","description":"Roadmap in a Kanban board"},{"name":"Landing Page","description":"Landing page with the lead capture"},{"name":"Forum","description":"Discussion forum"},{"name":"Wiki","description":"Wiki application"}]}
root@b6e440b0ffb6:/# 
```
However, in the container log I see the following:
```
Saltcorn listening on http://localhost:3000/
Saltcorn listening on http://localhost:3000/
Saltcorn listening on http://localhost:3000/
Saltcorn listening on http://localhost:3000/
FetchError: request to https://store.saltcorn.com/api/extensions failed, reason: connect ETIMEDOUT 104.21.17.44:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
FetchError: request to https://store.saltcorn.com/api/extensions failed, reason: connect ETIMEDOUT 172.67.221.60:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
fetch store error FetchError: request to https://store.saltcorn.com/api/packs?fields=name,description failed, reason: connect ETIMEDOUT 172.67.221.60:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
```
