### ISSUE TITLE
Error while creating view

### ISSUE THREAD

**Issue by Txikivasco** [saltcorn/saltcorn#1622]
Every time I try to create a filter view I get this error:

"An error occurred
Cannot read properties of undefined (reading 'reftable_name')

This happened only after updating to latest version

**Comment by glutamate** [comment]
Can you send a stack trace, or a full error from the crash log? are you on a tenant on saltcorn.com?

**Comment by Txikivasco** [comment]
yes, where is the crash log located?

**Comment by Txikivasco** [comment]
Nevermind, found it

id	
157
stack	
TypeError: Cannot read properties of undefined (reading 'reftable_name')
    at /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/filter.js:73:44
    at Array.map (<anonymous>)
    at builder (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/filter.js:68:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at applyAsync (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/utils.ts:53:39)
    at Workflow.runStep (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/workflow.ts:239:13)
    at /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/viewedit.js:562:19
message	
Cannot read properties of undefined (reading 'reftable_name')
occur_at	
Wed Feb 08 2023 12:48:50 GMT+0100 (hora estándar de Europa central)
tenant	
public
user_id	
1
body	
{
  "body": {}
}
url	
/viewedit/config/filter%20keyword%20edit
headers	
{
  "host": "kisib.arkeoworks.eus",
  "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
  "cookie": "connect.sid=s%3ANOQiTIlHLyq-L3kwGsa_kaYD7dcvuB3Z.xbpSKuwJ358R4EXhH5YPPLMXc8RbJDrYMEmsYtkZTFs",
  "referer": "http://kisib.arkeoworks.eus/viewedit/new",
  "x-real-ip": "185.193.9.137",
  "connection": "close",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
  "cache-control": "max-age=0",
  "accept-encoding": "gzip, deflate",
  "accept-language": "es-ES,es;q=0.9",
  "x-forwarded-for": "185.193.9.137",
  "x-forwarded-proto": "http",
  "x-forwarded-scheme": "http",
  "upgrade-insecure-requests": "1"
}

**Comment by glutamate** [comment]
if you are self hosting, on the url `/crashlog`

if you are a tenant on saltcorn.com send me the name.

**Comment by glutamate** [comment]
thanks. you have a field that is weird. what happens if you run a configuration check (go to `/admin/configuration-check`, or click configuration check under Settings -> About application -> System

**Comment by Txikivasco** [comment]
I get some errors

View Filter Ficha Tecnica config: Cannot read properties of undefined (reading 'reftable_name')
View filter keyword edit config: Cannot read properties of undefined (reading 'reftable_name')
View Filter Sello 1 config: Cannot read properties of undefined (reading 'reftable_name')
View filtro palabras clave ids config: Cannot read properties of undefined (reading 'reftable_name')
View View Prueba join render: In View Prueba join view (ListShowList viewtemplate):
View View Prueba join incorrectly configured: cannot find view Sello ID
In View Edit Ficha Tecnica, view when done undefined not found
In view ListUploads, field time does not exist in table uploads
In view Registrar Nuevo Sello, field idi does not exist in table Sello
In view Registrar Nuevo Sello, field idar does not exist in table Sello
In view Registrar Nuevo Sello, field enlaces_relacionados does not exist in table Sello
In view showupload, field time does not exist in table uploads
Configuration checks passed
Table Artifact OK
Table CSV Ciudades Sumerias OK
Table Iconographic keywords OK
Table Join IDS + IDAR OK
Table Logogramas OK
Table Sello OK
Table uploads OK
Table users OK
Page Búsqueda renders OK
Page Búsquedas Varias renders OK
Page Filtros de búsqueda renders OK
Page keywords sello classify renders OK
Page Kisib GIS renders OK
Page Logogramas renders OK
Page Page Edit Ficha Tecnica renders OK
Page Página de Bienvenida renders OK
Page Recursos online renders OK
View Artefacto ID (reducido inventory data) x5 renders OK
View Artefacto ID (reducido inventory data) config OK
View Artefactos Relacionados x6 renders OK
View Artefactos Relacionados config OK
View Añadir Nuevo Artefacto x6 renders OK
View Añadir Nuevo Artefacto config OK
View Añadir Nuevo Sello x6 renders OK
View Añadir Nuevo Sello config OK
View Corpus x6 renders OK
View Corpus config OK
View Data Explorer View x1 renders OK
View Data Explorer View config OK
View Edit Ficha Tecnica x6 renders OK
View Edit Ficha Tecnica config OK
View Edit iconographic keywords x1 renders OK
View Edit iconographic keywords config OK
View Ficha Técnica x5 renders OK
View Ficha Técnica config OK
View Filter Ficha Tecnica x1 renders OK
View filter keyword edit x1 renders OK
View Filter Logograma x1 renders OK
View Filter Logograma config OK
View Filter Sello 1 x1 renders OK
View filtro palabras clave ids x1 renders OK
View header sello keywords x5 renders OK
View header sello keywords config OK
View List filtro Logogramas x1 renders OK
View List filtro Logogramas config OK
View List Filtro Sello x1 renders OK
View List Filtro Sello config OK
View List View Artifact x1 renders OK
View List View Artifact config OK
View List View Sello x1 renders OK
View List View Sello config OK
View Listshowlist view sello x6 renders OK
View Listshowlist view sello config OK
View ListUploads x1 renders OK
View ListUploads config OK
View Logogramas Cards x5 renders OK
View Logogramas Cards config OK
View newupload x3 renders OK
View newupload config OK
View Registrar Nuevo Sello x6 renders OK
View Registrar Nuevo Sello config OK
View Relación altura diámetro sellos x6 renders OK
View Relación altura diámetro sellos config OK
View Sello ID (reducido inventory data) x5 renders OK
View Sello ID (reducido inventory data) config OK
View Show Artifact x5 renders OK
View Show Artifact config OK
View showupload x2 renders OK
View showupload config OK
View test sello casillas x5 renders OK
View test sello casillas config OK
View view FOS x5 renders OK
View view FOS config OK
View View List Join IDS + IDAR x1 renders OK
View View List Join IDS + IDAR config OK
View View Prueba join config OK

Otherwise the configuration cheks are passed

**Comment by Txikivasco** [comment]
the first four entries are related to the error from the issue (I tried to create more views just in case, but with the same result)

**Comment by glutamate** [comment]
ok, i no  longer think there is a problem with one of your fields

**Comment by glutamate** [comment]
fix coming up

**Comment by Txikivasco** [comment]
ok, thank you! looking forward to it!
