### ISSUE TITLE
calling an action raised an acorn error (?)

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1696]
**Describe the bug**
I added an event, called this event from a list view (action on row > action = event), got no error, nor action got executed, but container logs:
```
/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:3460

    var err = new SyntaxError(message);
              ^

SyntaxError: Unexpected token (1:6)

    at Parser.pp$4.raise (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:3460:15)

    at Parser.pp$9.unexpected (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:761:10)

    at Parser.pp$9.expect (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:755:28)

    at Parser.pp$5.parseObj (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:3081:14)

    at Parser.pp$5.parseExprAtom (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:2820:19)

    at Parser.pp$5.parseExprSubscripts (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:2636:21)

    at Parser.pp$5.parseMaybeUnary (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:2602:19)

    at Parser.pp$5.parseExprOps (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:2529:21)

    at Parser.pp$5.parseMaybeConditional (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:2512:21)

    at Parser.pp$5.parseMaybeAssign (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:2479:21)

    at Parser.pp$5.parseExpression (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:2442:21)

    at Function.parseExpressionAt (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:646:19)

    at parseExpressionAt (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/acorn/dist/acorn.js:5575:19)

    at transform_for_async (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/expression.ts:340:37)

    at get_async_expression_function (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/expression.ts:415:27)

    at Object.run (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/actions.js:660:17) {


```

Any idea?

**Comment by glutamate** [comment]
what is the action? Can you paste a screenshot of its configuration?

**Comment by j2l** [comment]
![image](https://user-images.githubusercontent.com/65325/224012301-dd82e2f9-8f5d-42f6-a9ff-85cbf1b50c77.png)
Maybe I misused it?

**Comment by j2l** [comment]
no formula, it was just as the screenshot.

**Comment by glutamate** [comment]
But do you have any API call triggers? like this: 

![Screenshot 2023-03-14 at 17 51 52](https://user-images.githubusercontent.com/43804/225094307-16c6e97d-57bc-4458-8460-980fd5f48810.png)

They will run when you emit this event.

**Comment by j2l** [comment]
Yes, that's it.
No channel.

**Comment by j2l** [comment]
Not sure what exactly you mean, sorry. 
It was nothing more than in the screenshot and default event: API + JS (empty code).
