### ISSUE TITLE
jquery linked to bootstrap?

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1736]
**Describe the bug**
When I remove bootstrap.min.js, I get this jQuery errror:
```
jquery-3.6.0.min.js:2 jQuery.Deferred exception: $(...).tab is not a function TypeError: $(...).tab is not a function
    at HTMLAnchorElement.<anonymous> (http://localhost:3000/static_assets/95961f73c8063b77/saltcorn.js:701:22)
    at Function.each (http://localhost:3000/static_assets/95961f73c8063b77/jquery-3.6.0.min.js:2:3003)
    at S.fn.init.each (http://localhost:3000/static_assets/95961f73c8063b77/jquery-3.6.0.min.js:2:1481)
    at $.fn.historyTabs (http://localhost:3000/static_assets/95961f73c8063b77/saltcorn.js:674:19)
    at HTMLDocument.initialize_page (http://localhost:3000/static_assets/95961f73c8063b77/saltcorn-common.js:572:63)
    at e (http://localhost:3000/static_assets/95961f73c8063b77/jquery-3.6.0.min.js:2:30038)
    at t (http://localhost:3000/static_assets/95961f73c8063b77/jquery-3.6.0.min.js:2:30340) undefined
S.Deferred.exceptionHook @ jquery-3.6.0.min.js:2
t @ jquery-3.6.0.min.js:2
jquery-3.6.0.min.js:2 Uncaught TypeError: $(...).tab is not a function
    at HTMLAnchorElement.<anonymous> (saltcorn.js:701:22)
    at Function.each (jquery-3.6.0.min.js:2:3003)
    at S.fn.init.each (jquery-3.6.0.min.js:2:1481)
    at $.fn.historyTabs (saltcorn.js:674:19)
    at HTMLDocument.initialize_page (saltcorn-common.js:572:63)
    at e (jquery-3.6.0.min.js:2:30038)
    at t (jquery-3.6.0.min.js:2:30340)
```
As you can see, it's not related to any script or code in the theme script. I removed every script just to make sure.

**Comment by glutamate** [comment]
@j2l what are you trying to do? Saltcorn requires both jquery and bootstrap js. I guess it could be possible to make bootstrap js optional, is that what you are looking for?

**Comment by j2l** [comment]
Yes, exactly, I'm working on a non-bootstrap theme (see my tickets in tabler) so I'd like to have bootstrap as an option.

**Comment by glutamate** [comment]
This specific issue is fixed in the latest release, do let me know if other issues arise when removing bootstrap javascript.
