### ISSUE TITLE
Update from 0.8.5-beta.8 to 0.8.5-rc.1 " X509Certificate is not a constructor "

### ISSUE THREAD

**Issue by SebaBecks** [saltcorn/saltcorn#1752]
_**after upgrading from version 0.8.5-beta.8 to version 0.8.5-rc.1 there is an error in the System tab**_

TypeError: X509Certificate is not a constructor
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/admin.js:778:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.

**_and in the Settings / Users and security / SSL tab_**

TypeError: X509Certificate is not a constructor
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/auth/admin.js:600:27
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/utils.js:239:19
    at handleReturn (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at handleReturn (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at Layer.handle [as handle_request] (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/route.js:144:13)
    at isAdmin (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/utils.js:76:5)
    at handleReturn (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at handleReturn (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at Layer.handle [as handle_request] (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/route.js:114:3)
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.

**Comment by glutamate** [comment]
@SebaBecks are you on node.js 14?

**Comment by SebaBecks** [comment]
> 

yes node.js v14.21.2

**Comment by glutamate** [comment]
this is fixed in the latest release (0.8.5-rc.2)

You may have difficulty upgrading since this error occurs on the upgrade screen. to upgrade:

1. use ssh to connect to your server
2. make sure you are the saltcorn user: `su saltcorn` and then `cd` to make sure you are in the saltcorn on user's home directory
3. run `npm install -g @saltcorn/cli@latest --unsafe`
4. restart the saltcorn process: become root (`exit` if you used su to become saltcorn) and then `systemctl restart saltcorn` - or you can just reboot the server

**Comment by SebaBecks** [comment]
Thank you very much, done, everything is working normally
