### ISSUE TITLE
Deletion of table index constraint doesn't work in tenants

### ISSUE THREAD

**Issue by pyhedgehog** [saltcorn/saltcorn#1754]
**Describe the bug**
Deletion of table index constraint doesn't work in non-default tenant.

**To Reproduce**
1. Create tenant.
2. Create table.
3. Create index constraint.
4. Attempt to drop it.
5. See error:
```
error: index "table_column_index" does not exist
    at Parser.parseErrorMessage (/opt/saltcorn/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/opt/saltcorn/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/opt/saltcorn/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/opt/saltcorn/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```
6. Constraint deleted, index -- not dropped.
 
**Expected behavior**
Index and corresponding constraint disappeared. No error message in progress.

**Comment by pyhedgehog** [comment]
No tenant mentioned:
https://github.com/saltcorn/saltcorn/blob/0281ca5f13e582464f02bb63012a86b076bdf185/packages/postgres/postgres.js#L357-L364
