### ISSUE TITLE
Fails to load page. Error message: "getState(...).getLayout(...).renderBody is not a function"

### ISSUE THREAD

**Issue by reclawe** [saltcorn/saltcorn#1805]
Trying to load a page results in this screen:

![image](https://user-images.githubusercontent.com/61644025/236932462-aa91e6de-35fb-4da7-8756-3bb996234932.png)

I checked all of the elements on the page and they load fine individually but for some reason the page doesn't work.

Full crash log here:

TypeError: getState(...).getLayout(...).renderBody is not a function
    at Object.page (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/page.ts:274:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:55:7)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:67:40)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:59:34)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:63:49)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:67:40)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:71:42)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:67:40)
    at traverse (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:75:3)
    at Page.run (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/page.ts:259:5)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/page.js:48:24

**Comment by christianhugoch** [comment]
I believe it is the adminlte theme that causes trouble, we have to add a little change to this plugin.

**Comment by christianhugoch** [comment]
Okay, it is fixed, but the adminlte theme is not ready to run in the mobile app.

**Comment by reclawe** [comment]
Thanks for the prompt response. Yeah it was the adminlte theme as you said. Uninstalled and reinstalled it. It loaded one of the embedded pages we have correctly but switching to the next from the Menu brings up the error again... until I refresh the page where it loads correctly. Still a bit buggy, we might have to do without it for now

**Comment by christianhugoch** [comment]
I believe you have multiple server running. If you want, you could try to click "Restart server" ("About application"/"System").

Let me know if that causes any trouble.

**Comment by reclawe** [comment]
Hey,

Thanks christian this worked for us! Appreciate the prompt response
