### ISSUE TITLE
Error accessing tables: "Cannot read property 'role' of undefined"

### ISSUE THREAD

**Issue by glimmung** [saltcorn/saltcorn#1911]
I have an old Digital Ocean Saltcorn appliance that has been running some scratch/dev stuff for ages. I normally only tinker with tenants, but recently  found that the root site has this issue - I get the error: -

"An error occurred
Cannot read property 'role' of undefined
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation."

...when trying to access the "Tables" option in the admin menu.

Other info: -
- The instance and all modules have been updated.
- The "Configuration Check" indicates no issues.
- This seems to only affect the root site, not the tenants.

It's not urgent, because there are only scratch sites on this server (anything with legs has been migrated to a production server), but I'd like to understand what happened and fix it if possible - I just don't know where to start, based on the message.

**Comment by glimmung** [comment]
I turned the dev stuff on, and got a more informative error message: -

TypeError: Cannot read property 'role' of undefined
    at getRole (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/common_lists.js:47:59)
    at Object.key (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/common_lists.js:63:22)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.ts:121:74
    at Array.map (<anonymous>)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.ts:118:22
    at Array.map (<anonymous>)
    at mkTable (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.ts:115:24)
    at tablesList (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/common_lists.js:49:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/tables.js:1073:22
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.

...but that still doesn't mean anything to me. 

Is the crashlog something different / more informative? Where would I find it?

Thinking more about the problem, I have a couple of other servers that have been up over the same time period, with no problems. However, this is the only one that is a DO appliance (the others are Docker and hand-installed on a Linode VM), and the least frequently accessed and least tinkered about with. I wonder if it has somehow skipped an upgrade step?
