### ISSUE TITLE
Login triggers don't work for me. 

### ISSUE THREAD

**Issue by cfredericksen** [saltcorn/saltcorn#1936]
**Describe the bug**
Login triggers do not run.

**To Reproduce**
1. I created a Login trigger with the following code:
```
var date = new Date();
for (var i = 0; i < 1; i++) {
    await Table.findOne({name: 'users'}).tryUpdateRow(({lastloggedin: date}), user.id);
}
```
2. If I run 'Test run', it updates the date in the users table based on the currently logged user. 
3. I set the table permissions to user
4. I see the logs when I run a 'Test run'
5. Nothing happens when a user logs in. No logs or no table update. 

**Expected behavior**
An event should be logged and the row should be updated. 

**Screenshots**

**Additional context**
I even tried updated a new table named 'logins' to try and update that one to test and nothing happened.

**Comment by Ingenu1ty** [comment]
I tried to reproduce the bug... And yes, you are right: nothing happens when a user logs in. 

**But If I run 'Test run',** I get the following error:
```
An error occurred 

In usersListTest view (List viewtemplate): Invalid time value 

A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.
``` 

crash log: 

```javascript 

id | 102
-- | --
stack | RangeError: Invalid time value     at Date.toISOString (<anonymous>)     at localeDateTime (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/index.ts:218:22)     at Object.run (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/types.js:1351:13)     at Object.key (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/viewable_fields.js:766:55)     at /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.ts:121:74     at Array.map (<anonymous>)     at /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.ts:118:22     at Array.map (<anonymous>)     at mkTable (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.ts:115:24)     at Object.run (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/list.js:639:21)     at View.run (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.ts:421:14)     at View.run_possibly_on_page (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.ts:515:18)     at /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/view.js:72:22
message | In usersListTest view (List viewtemplate): Invalid time value
occur_at | Wed Aug 02 2023 17:01:04 GMT+0000 (Coordinated Universal Time)
tenant | public
user_id | 2
body | "{\"body\":{}}"
url | /view/usersListTest
headers | {   "host": "localhost:3000",   "connection": "keep-alive",   "sec-ch-ua": "\"Not)A;Brand\";v=\"24\", \"Chromium\";v=\"116\"",   "sec-ch-ua-mobile": "?1",   "sec-ch-ua-platform": "\"Android\"",   "upgrade-insecure-requests": "1",   "user-agent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36",   "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",   "sec-fetch-site": "same-origin",   "sec-fetch-mode": "navigate",   "sec-fetch-user": "?1",   "sec-fetch-dest": "document",   "referer": "http://localhost:3000/crashlog",   "accept-encoding": "gzip, deflate, br",   "accept-language": "en-US,en;q=0.9,ru;q=0.8",   "cookie": "loggedin=true; connect.sid=s%3AenPgwNAYODUFEBBGlDhjhkHRzuZG9VpG.pLw659eO4M%2FhJfO3%2FpgLfuul%2BadacJkA9ZY3Upu%2FzNo" }


``` 

hope this helps someone fix this weird bug...

**Comment by cfredericksen** [comment]
@Ingenu1ty 

I updated my code to try to work around this issue. Changing from Date to just a string in a database. Still not working for me. 
```
const date = new Date();
const year = date.getFullYear();
const month = date.getMonth() + 1;
const day = date.getDate();

const withHyphens = [year, month, day].join('-');
console.log(withHyphens); // 👉️ "2023-7-25"

for (var i = 0; i < 1; i++) {
    await Table.findOne({name: 'Logins'}).tryInsertRow(({lastloggedin: withHyphens, user: user.id}));
}
return {notify: "Welcome!."};
```
Test trigger works great, event log is written
Login trigger doesnt work. I do get the Welcome message but no event log or container log.

**Comment by Ingenu1ty** [comment]
> Changing from Date to just a string in a database.

Yes, the date as a string works... but it's still just a workaround for the bug. I think that the date should be stored correctly in the "date field" :) 

Regarding the "login trigger" bug: 

I found that "login trigger" works if I use "blocks type" as action type... But in "blocks actions" I can't access the current user object :(
![Sc_blckly](https://github.com/saltcorn/saltcorn/assets/138471707/88c01cdb-fc1c-41f4-9ace-6af4a5bbae43)

**Comment by glutamate** [comment]
Login triggers currently run on the root tenant only, so you won't see them on saltcorn.com, but if you host a single tenancy application that should work fine.

**Comment by cfredericksen** [comment]
Thank for your response @glutamate. I will migrate to a root tenant for my container. Closing now!
