### ISSUE TITLE
Issue with Embedded View

### ISSUE THREAD

**Issue by lookforhisface** [saltcorn/saltcorn#2188]
I have a view which shows a person and then another view that shows animals owned by that person. If I do not tell the view to only show animals owned by the person, the page renders fine but shows all animals in the animals table. Once I try to set the embedded view to only show animals owned by that person it wigs out with the following errors:

Error on page:

An error occurred
In Person Information view (Show viewtemplate):
In List Animals view (List viewtemplate):
Cannot read properties of null (reading 'replace')
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.

Error output:
{
  "url": "/view/Person%20Information?id=2",
  "body": {
    "body": {}
  },
  "stack": "TypeError: Cannot read properties of null (reading 'replace')\n    at sqlsanitizeAllowDots (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/db-common/internal.ts:35:16)\n    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/db-common/internal.ts:272:27\n    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/db-common/internal.ts:415:32\n    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/db-common/internal.ts:364:39\n    at Array.map ()\n    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/db-common/internal.ts:364:11\n    at Array.map ()\n    at mkWhere (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/db-common/internal.ts:513:27)\n    at Table.getJoinedQuery (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/table.ts:2973:38)\n    at Table.getJoinedRows (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/table.ts:3135:18)\n    at listQuery (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/list.js:824:30)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Object.run (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/list.js:560:30)\n    at View.run (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.ts:457:14)\n    at Object.view (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/show.js:570:13)\n    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:58:44)",
  "tenant": "hhsc",
  "headers": {
    "host": "hhsc.ltintegration.net",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "cf-ray": "83d371576e5606f0-ATL",
    "cookie": "__gsas=ID=c9fd37c0062db1b5:T=1701112685:RT=1701112685:S=ALNI_MbpgaSucGoLnNy_QvuGfY5IHnPKPw; connect.sid=s%3AdwoEGnDpNtJTbR6u7wmNvNxIMwdWdvB6.0GFrwvxafme0El9ac7GDTrfjDLIT6NGr53X2O5MuW2A",
    "referer": "https://hhsc.ltintegration.net/page/People",
    "cdn-loop": "cloudflare",
    "priority": "u=0, i",
    "sec-ch-ua": "\"Google Chrome\";v=\"119\", \"Chromium\";v=\"119\", \"Not?A_Brand\";v=\"24\"",
    "cf-visitor": "{\"scheme\":\"https\"}",
    "connection": "keep-alive",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "cf-ipcountry": "US",
    "cf-warp-tag-id": "2ead9dd6-12b9-41e8-ab3d-99600c3b92f1",
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "same-origin",
    "sec-fetch-user": "?1",
    "accept-encoding": "gzip",
    "accept-language": "en-US,en;q=0.9",
    "x-forwarded-for": "71.28.124.74",
    "cf-connecting-ip": "71.28.124.74",
    "sec-ch-ua-mobile": "?0",
    "x-forwarded-proto": "https",
    "sec-ch-ua-platform": "\"macOS\"",
    "upgrade-insecure-requests": "1"
  },
  "message": "In Person Information view (Show viewtemplate):\nIn List Animals view (List viewtemplate):\nCannot read properties of null (reading 'replace')",
  "user_id": 1,
  "occur_at": "2023-12-29T16:33:05.253Z"
}

**Comment by christianhugoch** [comment]
I'll provide a fix soon

**Comment by christianhugoch** [comment]
it should work again in [v0.9.3-beta.2](https://github.com/saltcorn/saltcorn/commit/7f9bbfe57549985a2fae96aedd93c16f8ad3dad7)
