### ISSUE TITLE
Textfield in edit form disapears since 0.9.4-beta.18

### ISSUE THREAD

**Issue by SaschaMn** [saltcorn/saltcorn#2330]
**Describe the bug**
When dropping a textfield into an edit form, when I'm trying to edit the hello world text, I can't click in the text field and change ist. 
The menu appears and the textfield disappears. No matter what I put into the "Text to display" Box, it won't be saved. So I just can can add Hello world right now. 

![bug1](https://github.com/saltcorn/saltcorn/assets/159874339/155ac792-6025-41d1-bebb-a32f99de24f2)

**Comment by glutamate** [comment]
Hi @SaschaMn which browser are you using? I don't see this problem in Chrome or Firefox

**Comment by SaschaMn** [comment]
> Hi @SaschaMn which browser are you using? I don't see this problem in Chrome or Firefox

Hey Tom, I‘m using Firefox and it seems that this was a temporary problem. Today I was able to change text and text style. Text still disappears sometimes in the edit view, but is correctly displayed on rendered view.

**Comment by glutamate** [comment]
Just saw this as well, here is console error

```
Refused to execute script from 'http://localhost:3000/static_assets/b4e47930ea8f1410/ckeditor/config.js?t=L7C8' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
authorshow:1 Refused to apply style from 'http://localhost:3000/static_assets/b4e47930ea8f1410/ckeditor/skins/moono-lisa/editor.css?t=L7C8' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
authorshow:1 Refused to execute script from 'http://localhost:3000/static_assets/b4e47930ea8f1410/ckeditor/lang/en-gb.js?t=L7C8' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
ckeditor.js:260 Uncaught TypeError: Cannot set properties of undefined (setting 'dir')
    at Object.d (ckeditor.js:260:54)
    at y (ckeditor.js:261:181)
    at Array.z (ckeditor.js:261:336)
    at x (ckeditor.js:261:420)
    at C.CKEDITOR.env.ie.f.$.onerror (ckeditor.js:262:429)
d @ ckeditor.js:260
y @ ckeditor.js:261
z @ ckeditor.js:261
x @ ckeditor.js:261
C.CKEDITOR.env.ie.f.$.onerror @ ckeditor.js:262
error (async)
C @ ckeditor.js:262
load @ ckeditor.js:263
load @ ckeditor.js:260
p @ ckeditor.js:279
(anonymous) @ ckeditor.js:279
b @ ckeditor.js:558
loadPart @ ckeditor.js:560
k @ ckeditor.js:279
(anonymous) @ ckeditor.js:278
p @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13
fireOnce @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fireOnce @ ckeditor.js:13
l @ ckeditor.js:276
(anonymous) @ ckeditor.js:276
callback @ ckeditor.js:263
y @ ckeditor.js:261
z @ ckeditor.js:261
x @ ckeditor.js:261
C.CKEDITOR.env.ie.f.$.onerror @ ckeditor.js:262
error (async)
C @ ckeditor.js:262
load @ ckeditor.js:263
a @ ckeditor.js:263
(anonymous) @ ckeditor.js:263
l @ ckeditor.js:276
h @ ckeditor.js:278
(anonymous) @ ckeditor.js:275
(anonymous) @ ckeditor.js:30
setTimeout (async)
setTimeout @ ckeditor.js:30
a @ ckeditor.js:275
CKEDITOR.inline @ ckeditor.js:361
(anonymous) @ builder_bundle.js:148444
Promise.then (async)
value @ builder_bundle.js:148444
value @ builder_bundle.js:148444
commitLifeCycles @ builder_bundle.js:25894
commitLayoutEffects @ builder_bundle.js:28883
callCallback @ builder_bundle.js:6268
invokeGuardedCallbackDev @ builder_bundle.js:6317
invokeGuardedCallback @ builder_bundle.js:6372
commitRootImpl @ builder_bundle.js:28621
unstable_runWithPriority @ builder_bundle.js:31764
runWithPriority$1 @ builder_bundle.js:17119
commitRoot @ builder_bundle.js:28461
finishSyncRender @ builder_bundle.js:27887
performSyncWorkOnRoot @ builder_bundle.js:27873
(anonymous) @ builder_bundle.js:17169
unstable_runWithPriority @ builder_bundle.js:31764
runWithPriority$1 @ builder_bundle.js:17119
flushSyncCallbackQueueImpl @ builder_bundle.js:17164
flushSyncCallbackQueue @ builder_bundle.js:17152
flushPendingDiscreteUpdates @ builder_bundle.js:27927
flushDiscreteUpdates @ builder_bundle.js:27907
flushDiscreteUpdatesIfNeeded @ builder_bundle.js:6909
dispatchDiscreteEvent @ builder_bundle.js:10247
Show 23 more frames
Show less
builder_bundle.js:148444 Uncaught TypeError: Cannot read properties of undefined (reading 'setStyles')
    at c.value (builder_bundle.js:148444:23839)
    at commitLifeCycles (builder_bundle.js:25915:22)
    at commitLayoutEffects (builder_bundle.js:28883:7)
    at HTMLUnknownElement.callCallback (builder_bundle.js:6268:14)
    at Object.invokeGuardedCallbackDev (builder_bundle.js:6317:16)
    at invokeGuardedCallback (builder_bundle.js:6372:31)
    at commitRootImpl (builder_bundle.js:28621:9)
    at unstable_runWithPriority (builder_bundle.js:31764:12)
    at runWithPriority$1 (builder_bundle.js:17119:10)
    at commitRoot (builder_bundle.js:28461:3)
value @ builder_bundle.js:148444
commitLifeCycles @ builder_bundle.js:25915
commitLayoutEffects @ builder_bundle.js:28883
callCallback @ builder_bundle.js:6268
invokeGuardedCallbackDev @ builder_bundle.js:6317
invokeGuardedCallback @ builder_bundle.js:6372
commitRootImpl @ builder_bundle.js:28621
unstable_runWithPriority @ builder_bundle.js:31764
runWithPriority$1 @ builder_bundle.js:17119
commitRoot @ builder_bundle.js:28461
finishSyncRender @ builder_bundle.js:27887
performSyncWorkOnRoot @ builder_bundle.js:27873
(anonymous) @ builder_bundle.js:17169
unstable_runWithPriority @ builder_bundle.js:31764
runWithPriority$1 @ builder_bundle.js:17119
flushSyncCallbackQueueImpl @ builder_bundle.js:17164
flushSyncCallbackQueue @ builder_bundle.js:17152
flushPendingDiscreteUpdates @ builder_bundle.js:27927
flushDiscreteUpdates @ builder_bundle.js:27907
flushDiscreteUpdatesIfNeeded @ builder_bundle.js:6909
dispatchDiscreteEvent @ builder_bundle.js:10247
Show 21 more frames
Show less
ckeditor.js:260 Uncaught TypeError: Cannot set properties of undefined (setting 'dir')
    at Object.d (ckeditor.js:260:54)
    at y (ckeditor.js:261:181)
    at z (ckeditor.js:261:336)
    at C (ckeditor.js:261:449)
    at Object.load (ckeditor.js:263:29)
    at Object.load (ckeditor.js:260:121)
    at p (ckeditor.js:279:93)
    at ckeditor.js:279:58
    at b (ckeditor.js:558:492)
    at Object.loadPart (ckeditor.js:560:235)
d @ ckeditor.js:260
y @ ckeditor.js:261
z @ ckeditor.js:261
C @ ckeditor.js:261
load @ ckeditor.js:263
load @ ckeditor.js:260
p @ ckeditor.js:279
(anonymous) @ ckeditor.js:279
b @ ckeditor.js:558
loadPart @ ckeditor.js:560
k @ ckeditor.js:279
(anonymous) @ ckeditor.js:278
p @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13
fireOnce @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fireOnce @ ckeditor.js:13
l @ ckeditor.js:276
h @ ckeditor.js:278
(anonymous) @ ckeditor.js:275
(anonymous) @ ckeditor.js:30
setTimeout (async)
setTimeout @ ckeditor.js:30
a @ ckeditor.js:275
CKEDITOR.inline @ ckeditor.js:361
(anonymous) @ builder_bundle.js:148444
Promise.then (async)
value @ builder_bundle.js:148444
value @ builder_bundle.js:148444
commitLifeCycles @ builder_bundle.js:25894
commitLayoutEffects @ builder_bundle.js:28883
callCallback @ builder_bundle.js:6268
invokeGuardedCallbackDev @ builder_bundle.js:6317
invokeGuardedCallback @ builder_bundle.js:6372
commitRootImpl @ builder_bundle.js:28621
unstable_runWithPriority @ builder_bundle.js:31764
runWithPriority$1 @ builder_bundle.js:17119
commitRoot @ builder_bundle.js:28461
finishSyncRender @ builder_bundle.js:27887
performSyncWorkOnRoot @ builder_bundle.js:27873
(anonymous) @ builder_bundle.js:17169
unstable_runWithPriority @ builder_bundle.js:31764
runWithPriority$1 @ builder_bundle.js:17119
flushSyncCallbackQueueImpl @ builder_bundle.js:17164
flushSyncCallbackQueue @ builder_bundle.js:17152
flushPassiveEffectsImpl @ builder_bundle.js:28963
unstable_runWithPriority @ builder_bundle.js:31764
runWithPriority$1 @ builder_bundle.js:17119
flushPassiveEffects @ builder_bundle.js:28900
flushDiscreteUpdates @ builder_bundle.js:27910
flushDiscreteUpdatesIfNeeded @ builder_bundle.js:6909
dispatchDiscreteEvent @ builder_bundle.js:10247
Show 26 more frames
Show less
ckeditor.js:260 Uncaught TypeError: Cannot set properties of undefined (setting 'dir')
    at Object.d (ckeditor.js:260:54)
    at y (ckeditor.js:261:181)
    at z (ckeditor.js:261:336)
    at C (ckeditor.js:261:449)
    at Object.load (ckeditor.js:263:29)
    at Object.load (ckeditor.js:260:121)
    at p (ckeditor.js:279:93)
    at ckeditor.js:279:58
    at b (ckeditor.js:558:492)
    at Object.loadPart (ckeditor.js:560:235)

```
