### ISSUE TITLE
Emails Errors

### ISSUE THREAD

**Issue by cfredericksen** [saltcorn/saltcorn#2416]
**Describe the bug**
"Send verification email"  and "Send Password reset email" fail.

#### Send verification email
"Verification email sender error:" (in the gui)
```
insert into "public"."_sc_event_log"("event_type","channel","occur_at","user_id","payload") values($1,$2,$3,$4,$5) returning id [
  'Update',
  'users',
  2024-04-05T15:54:15.068Z,
  undefined,
  {
    verification_token: 'e1ecfc99-4920-44c1-8882-b8c3b36d7a27',
    id: 121
  }
]
```
#### Send Password reset email failure

```
Error: Can't send mail - all recipients were rejected: 550 relay not permitted
    at SMTPConnection._formatError (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/nodemailer/lib/smtp-connection/index.js:798:19)
    at SMTPConnection._actionRCPT (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/nodemailer/lib/smtp-connection/index.js:1667:28)
    at SMTPConnection.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/nodemailer/lib/smtp-connection/index.js:1620:30)
    at SMTPConnection._processResponse (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/nodemailer/lib/smtp-connection/index.js:982:20)
    at SMTPConnection._onData (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/nodemailer/lib/smtp-connection/index.js:763:14)
    at Socket.SMTPConnection._onSocketData (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.
```

**To Reproduce**
Settings -> Users and securuty -> pick a user and send password reset or send verification

**Expected behavior**
Emails would work just like they did prior to version 0.9.5-beta.14.

**Additional context**
"Send test email" works just fine.

**Comment by cfredericksen** [comment]
This works now with beta version 21.
