### ISSUE TITLE
Oauth2: Unknown authentication strategy "oauth2"

### ISSUE THREAD

**Issue by troem** [saltcorn/saltcorn#2477]
I try to setup oauth2 with saltcorn. 
Whenever I try to login, I receive the following error message:

`	
Error: Unknown authentication strategy "oauth2"
    at attempt (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/passport/lib/middleware/authenticate.js:193:39)
    at authenticate (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/auth/routes.js:1148:55
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/utils.js:242:19
    at handleReturn (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at handleReturn (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/index.js:284:15
    at param (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/index.js:365:14)
    at param (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/express/lib/router/index.js:421:3)`

Thank you for any help.

**Comment by troem** [comment]
Restart of saltcorn was required - now the OAuth is working
