### ISSUE TITLE
Triger activate triger

### ISSUE THREAD

**Issue by anteolic** [saltcorn/saltcorn#2688]
Saltcorn insert triger not work when i insert row with js code from other triger

**Comment by glutamate** [comment]
@anteolic Could you please give more details of the configuration, e.g. post screenshot of the send email trigger and the other trigger. Also, have you configured SMTP settings?

**Comment by anteolic** [comment]
Mail is working when you press TEST RUN, but when trigger is triggered with other triger than is not working. 
I made a system with due date, and one trigger which every 5 minutes check main table, and if some due date is near it create new row in other table, and this new row trigger email sending
I use Saltcorn on WIndows with sqlite
This is error:

ERROR: TypeError: Cannot read properties of undefined (reading 'email')
    at Object.run (C:\Users\anteo\AppData\Roaming\npm\node_modules\@saltcorn\cli\node_modules\@saltcorn\data\base-plugin\actions.js:599:26)
    at Trigger.trigger.run (C:\Users\anteo\AppData\Roaming\npm\node_modules\@saltcorn\cli\node_modules\@saltcorn\data\models\trigger.ts:442:18)
    at Function.runTableTriggers (C:\Users\anteo\AppData\Roaming\npm\node_modules\@saltcorn\cli\node_modules\@saltcorn\data\models\trigger.ts:313:35)
    at Table.insertRow (C:\Users\anteo\AppData\Roaming\npm\node_modules\@saltcorn\cli\node_modules\@saltcorn\data\models\table.ts:1932:35)
    at Table.tryInsertRow (C:\Users\anteo\AppData\Roaming\npm\node_modules\@saltcorn\cli\node_modules\@saltcorn\data\models\table.ts:1988:18)
    at evalmachine.<anonymous>:14:5
    at Object.run_code [as run] (C:\Users\anteo\AppData\Roaming\npm\node_modules\@saltcorn\cli\node_modules\@saltcorn\data\base-plugin\actions.js:175:10)
    at C:\Users\anteo\AppData\Roaming\npm\node_modules\@saltcorn\cli\node_modules\@saltcorn\server\routes\actions.js:816:16

**Comment by anteolic** [comment]
When on email triger Recipient email adress is FIXED, there is no error.
