### ISSUE TITLE
Upgrading Saltcorn droplet from beta.17 to rc1 fails

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2748]
Initially everything worked as expected, but after the usual warnings about deprecated packages nothing happened anymore. Foolishly enough I reloaded the page and the server has refused to connect ever since. I've restarted the droplet and accessed the console to manually restart saltcorn, but I get the following error message:

```
saltcorn@salt:/root$ saltcorn serve
Error reading mjmlconfig :  Error: EACCES: permission denied, open '/root/.mjmlconfig'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at readMjmlConfig (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/mjml-core/lib/helpers/mjmlconfig.js:38:43)
    at handleMjmlConfig (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/mjml-core/lib/helpers/mjmlconfig.js:146:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/mjml-core/lib/index.js:506:27)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/mjml/lib/index.js:12:41)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/root/.mjmlconfig'
}
app-locale create error [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/dist/app-locales'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/dist/app-locales'
}
    Error: ENOENT: no such file or directory, open 
    '/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/dist/app-locales/public/en.json'
    Code: ENOENT
```

**Comment by iron3oxide** [comment]
As a side note: maybe it would be helpful to have an option in the CLI to upgrade/downgrade/install a different version in case an update makes the UI inaccessible

**Comment by glutamate** [comment]
you current directory is `/root` to which you do not have write permissions

**Comment by glutamate** [comment]
also maybe you did an upgrade as root?

**Comment by iron3oxide** [comment]
> you current directory is `/root` to which you do not have write permissions

:facepalm: true, however running from `/` yields the same error:
```
saltcorn@salt:/$ saltcorn serveapp-locale create error [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/dist/app-locales'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/dist/app-locales'
}
    Error: ENOENT: no such file or directory, open 
    '/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/dist/app-locales/public/en.json'
    Code: ENOENT
```



> also maybe you did an upgrade as root?

I doubt it, I simply pressed the upgrade button in the system settings. Hadn't even logged into the console as root before that

**Comment by glutamate** [comment]
you also dont have write permission on `/` you should run from home (`cd ~`). But this will only solve the mjml config problem.

Check which saltcorn is running by `which saltcorn`. On the digitalocean droplets, and i believe also with systems installed with `npx saltcorn-install`, this should be `/home/saltcorn/.local/bin/saltcorn` - it should be somewhere in the saltcorn users home dir.

but for some reason your system is running from somewhere in /usr/local/lib - you could do `npm install -g @saltcorn/cli --unsafe` as saltcorn, then check if /home/saltcorn/.local/bin/saltcorn exists, if it does then delete the dir that `which saltcorn` is running from as root

**Comment by iron3oxide** [comment]
Well this has produced a new error so I'd call it a success:
```
saltcorn@salt:~$ saltcorn serve
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error: Code: ERR_MODULE_NOT_FOUND; The provided arguments length (2) does not match the required ones (3).
This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at new NodeError (node:internal/errors:405:5)
    at assert (node:internal/assert:14:11)
    at getMessage (node:internal/errors:451:5)
    at new NodeError (node:internal/errors:379:21)
    at legacyMainResolve (node:internal/modules/esm/resolve:218:9)
    at packageResolve (node:internal/modules/esm/resolve:903:14)
    at moduleResolve (node:internal/modules/esm/resolve:973:20)
    at defaultResolve (node:internal/modules/esm/resolve:1193:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25) {
  code: 'ERR_INTERNAL_ASSERTION'
}

Node.js v18.19.0
```
I had to remove the /usr/local/bin saltcorn, seems I installed the CLI as root again because naturally the root user had no access to it. Any idea what might have caused this new error?

**Comment by glutamate** [comment]
never seen that, any idea @christianhugoch ?

**Comment by glutamate** [comment]
best thing to do is probably start again:

```
rm -rf /home/saltcorn/.local/lib/node_modules
npm install -g @saltcorn/cli --unsafe
npm install -g sd-notify
```

**Comment by iron3oxide** [comment]
That (and restarting the droplet) resolved it, thank you very much!
