### ISSUE TITLE
Probleb - If admin deleted field (column in table) the Saltcorn should delete this field from view or ...

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#319]
Or do some else to avoid the exceptions on run time like:

User
TypeError: Cannot read property 'type' of undefined
    at new Field (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/field.js:13:12)
    at /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/list.js:118:17
    at Array.forEach (<anonymous>)
    at Object.get_state_fields (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/list.js:116:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async View.get_state_fields (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.js:41:14)
    at async View.get_state_form (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.js:207:22)
    at async /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/view.js:29:26
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.

**Comment by glutamate** [comment]
fixed in #320 - list, show and edit will ignore non-existing fields. I need to test omitted join fields

**Comment by glutamate** [comment]
join fields fixed in #321
