### ISSUE TITLE
[Markdown] Exception on empty values

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#335]
The scenario:

1.  Open Edit View for table record with empty markdown field

2. Close Edit.

3. You will receive message:
![image](https://user-images.githubusercontent.com/327030/95921584-35a4c100-0dba-11eb-9018-f5c354d4a247.png)

4. Try to open List View for this table. You'll receive exception:

Internal Error
Error: Input data should be a String
    at MarkdownIt.parse (/home/saltcorn/plugin_packages/markdown-it/lib/index.js:519:11)
    at MarkdownIt.render (/home/saltcorn/plugin_packages/markdown-it/lib/index.js:544:36)
    at Object.run (/home/saltcorn/plugin_packages/@saltcorn/markdown/markdown.js:18:44)
    at Object.key (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/viewable_fields.js:160:59)
    at /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.js:95:73
    at Array.map (<anonymous>)
    at /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.js:94:20
    at Array.map (<anonymous>)
    at /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.js:91:22
    at newf (/usr/lib/node_modules/@saltcorn/cli/node_modules/contractis/contract.js:66:45)
    at Object.run (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/list.js:211:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async View.run (/usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.js:141:12)
    at async /usr/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/view.js:28:20
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.

**Comment by glutamate** [comment]
fixed in updated markdown - you may need to update your plugins
