### ISSUE TITLE
Date error

### ISSUE THREAD

**Issue by jekroll555** [saltcorn/saltcorn#477]
This is a Windows 10 install using SQLite. This is from reading the Crash Log, I've received it a couple other places with a common error...

ContractViolation: value 1608221105378 violates contract class("Date") (instance variable "occur_at")
    at module.exports (C:\Users\jkroll\.local\node_modules\@saltcorn\cli\node_modules\contractis\check.js:5:11)
    at C:\Users\jkroll\.local\node_modules\@saltcorn\cli\node_modules\contractis\contract.js:108:9
    at Array.forEach (<anonymous>)
    at check_vars (C:\Users\jkroll\.local\node_modules\@saltcorn\cli\node_modules\contractis\contract.js:107:38)
    at Function.contract_class [as class] (C:\Users\jkroll\.local\node_modules\@saltcorn\cli\node_modules\contractis\contract.js:116:3)
    at new Crash (C:\Users\jkroll\.local\node_modules\@saltcorn\cli\node_modules\@saltcorn\data\models\crash.js:18:19)
    at C:\Users\jkroll\.local\node_modules\@saltcorn\cli\node_modules\@saltcorn\data\models\crash.js:22:26
    at Array.map (<anonymous>)
    at Function.find (C:\Users\jkroll\.local\node_modules\@saltcorn\cli\node_modules\@saltcorn\data\models\crash.js:22:15)
    at async C:\Users\jkroll\.local\node_modules\@saltcorn\cli\node_modules\@saltcorn\server\routes\crashlog.js:49:21

**Comment by glutamate** [comment]
fixed in https://github.com/saltcorn/saltcorn/pull/478
