### ISSUE TITLE
Problem with Discover table

### ISSUE THREAD

**Issue by enojaroff** [saltcorn/saltcorn#828]
Hi,
I'm trying to use Saltcorn with an existing database.
I select tables using "Discover tables" function. With some tables, it work fine; but with others, I get the following error:

TypeError: Cannot read property 'fields' of undefined
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/discovery.js:161:32
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/discovery.js:156:14
    at Array.forEach (<anonymous>)
    at discover_tables (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/discovery.js:155:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/tables.js:244:18

Table names does'nt contain any special characters, and fields type are quite simple (integer, var char).

Does anyone have an idea ?

**Comment by enojaroff** [comment]
Looking into code, I found an explanation : it's in saltcorn/packages/saltcorn-data/models/discovery.js, in discover_tables function. 
When importing tables with Discovery command, if a table has a foreign key pointing to another table, function will try to find that table in the list of tables (tableNames) being imported. That causes error if not found.
In my case, table was already imported.
