### ISSUE TITLE
arm64 docker image?

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#860]
After playing with my local docker, I tried the docker-compose in the raspi local server and got error.
`standard_init_linux.go:219: exec user process caused: exec format error`
which, I guess, means the image is not arm64 friendly :(
Since NodeJS is already universal, if it's not too much work, would it be possible to automatically deploy arm64 images?

**Comment by glutamate** [comment]
saltcorn definitely works on raspian, but I have not run it in a docker image, only directly as a systemd unit. What's the best way for me to build and push docker images for arm64? I have a Mac M1 and a rasppi, do they build and use interchangeable docker images?

**Comment by j2l** [comment]
I think you can build multi-arch images in one shot: https://www.docker.com/blog/multi-arch-images/
For this kind of package, docker-compose simply solves the arch by itself (uname -s & "-" & uname -m) so the docker-compose.yml remains valid (saltcorn/saltcorn:latest).

**Comment by j2l** [comment]
I'm trying to buildx both amd64 and arm64 images but pupeteer 4.0.1 (for lerna) is not seeing chromium.
See https://github.com/puppeteer/puppeteer/issues/6622 but it also happens on Ubuntu.
I do have chromium-browser:
```
apt list chromium-browser
Listing... Done
chromium-browser/hirsute 1:85.0.4183.83-0ubuntu2 amd64
```
According to the issue, it looks like it is fixed in pupeteer 10.

Can you upgrade pupeteer?

Also, when I only build amd64, I don't get how to link it to the db image.
Could you please let me know how to do it?
Thanks

For future readers, full error is:
```
#17 2.980 lerna notice cli v4.0.0                                                                                                                                                                            
#17 3.427 lerna info Bootstrapping 10 packages                                                                                                                                                               
#17 3.752 lerna info Installing external dependencies                                                                                                                                                        
#17 132.7 lerna ERR! npm install exited 1 in '@saltcorn/e2e'                                                                                                                                                 
#17 132.7 lerna ERR! npm install stdout:
#17 132.8 
#17 132.8 > puppeteer@4.0.1 install /opt/saltcorn/packages/e2e/node_modules/puppeteer
#17 132.8 > node install.js
#17 132.8 
#17 132.8 lerna ERR! npm install stderr:
#17 132.8 The chromium binary is not available for arm64: 
#17 132.8 If you are on Ubuntu, you can install with: 
#17 132.8 
#17 132.8  apt-get install chromium-browser
#17 132.8 
#17 132.8 /opt/saltcorn/packages/e2e/node_modules/puppeteer/lib/BrowserFetcher.js:112
#17 132.8             throw new Error();
#17 132.8             ^
#17 132.8 
#17 132.8 Error
#17 132.8     at /opt/saltcorn/packages/e2e/node_modules/puppeteer/lib/BrowserFetcher.js:112:19
#17 132.8     at FSReqCallback.oncomplete (fs.js:191:21)
#17 132.8 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
#17 132.8 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#17 132.8 
#17 132.8 npm ERR! code ELIFECYCLE
#17 132.8 npm ERR! errno 1
#17 132.8 npm ERR! puppeteer@4.0.1 install: `node install.js`
#17 132.8 npm ERR! Exit status 1
#17 132.8 npm ERR! 
#17 132.8 npm ERR! Failed at the puppeteer@4.0.1 install script.
#17 132.8 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#17 132.8 
#17 132.8 npm ERR! A complete log of this run can be found in:
#17 132.8 npm ERR!     /root/.npm/_logs/2021-09-29T13_20_29_979Z-debug.log
#17 132.8 lerna ERR! npm install exited 1 in '@saltcorn/e2e'
#17 132.8 lerna WARN complete Waiting for 7 child processes to exit. CTRL-C to exit immediately.
------
Error: failed to solve: process "/bin/sh -c lerna bootstrap" did not complete successfully: exit code: 1
```

**Comment by j2l** [comment]
Any news on this one?
My Chromium is amd64 in facts, but I guess pupeteer could get an arm64 to build multi-arch from any platform.

**Comment by glutamate** [comment]
I spent some time fighting puppeteer and chromium, to get print page to PDF
functionality working. I can look at this next. what command are you using
to build?

**Comment by glutamate** [comment]
I couldn't get buildx to work - I got a different error when trying to cross build.

However, I installed Docker on a raspberry pi 4 and was able to build there. I didn't get the same error as @j2l, but in #950 I introduced some changes to make the build more resilient against this type of errors, hopefully it should build for you.

**Comment by ThRPctmylSgltwH** [comment]
This is marked as closed but I just tried to run the docker container on a Raspberry PI 5 without success due to not supporting arm64. Is the container multi-arch? I used the docker-compose.yml in the examples/test folder.

**Comment by J-C-P** [comment]
Hi,
Same question as my fellow camarade.
Is it planned ?
I try to run a docker container in a Oracle VPS server and I face the same issue.
Thanks a lot :-)
