### ISSUE TITLE
fix for color issue

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#939]
When I change color to formula, it's populated with `#FFFFFF`
But it doesn't work and breaks the internet:
```
evalmachine.<anonymous>:1
({ability,chores,creativity,en,experience,fr,freq,gratitude,health,id,image,kindness,loving,proof,social,trust,when,work}, user)=>(#FFFFFF77)
                                                                                                                                   ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:102:7)
    at createScript (vm.js:262:10)
    at Object.runInNewContext (vm.js:303:10)
    at get_expression_function (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/expression.js:108:13)
    at evalMaybeExpr (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/show.js:415:17)
    at Object.container (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/show.js:450:7)
    at go (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.js:7:29)
    at go (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.js:18:40)
    at traverseSync (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.js:26:3)
    at render (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/viewtemplates/show.js:420:3)
```

While `'#FFFFFF'`
![image](https://user-images.githubusercontent.com/65325/136805393-8dbcec2f-19b3-4c62-925a-bb9c33358447.png)
is working fine

That's the way (uh huh, uh huh) I like it

**Comment by glutamate** [comment]
ah, i understand. let me see what i can do about the defult.
