### ISSUE TITLE
0.6.1-beta.0 JSgrid BUG: plugin: get_viewable_fields is not defined

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#983]
Installed locally from github
```
ReferenceError: In table_grid view (JsGrid viewtemplate):
get_viewable_fields is not defined
    at Object.run (/opt/saltcorn/plugin_packages/@saltcorn/jsgrid/index.js:99:19)
    at async View.run (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.js:281:14)
    at async View.run_possibly_on_page (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.js:311:18)
    at async /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/view.js:42:22
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.
```
I'm not sure who's playing the squirrel here :smile:

**Comment by glutamate** [comment]
i never finished that plugin, sorry. in any case I will probably switch the admin grid editor to Tabulator and then also do a plug-in for that instead.

**Comment by j2l** [comment]
Oh, nice! Tabulator is coming soon?
jsgrid plugin was working fine around 0.5.X. I wonder what happened.

**Comment by j2l** [comment]
Closing this one to lower my open tickets :smile:
